"""
Agent 5: Patient Translation Communicator

Description:
This agent bridges the gap between cold clinical data and human empathy. It takes the complex physiological diagnostics generated by Agent 4 and rewrites them into warm, safe, and easily understandable language. It ensures the patient feels heard by generating an empathetic summary and gently explains the 'why' behind their symptoms.
"""

from pydantic import BaseModel, Field
from typing import List

class PatientCommunicationSchema(BaseModel): 
    empathetic_summary: str = Field(...)
    understanding_the_why: str = Field(...)
    gentle_next_steps: List[str] = Field(...)

def execute_agent_5(client, agent_1_json_payload: str, agent_4_json_payload: str):
    system_prompt = "You are Agent 5 (Patient Translation Communicator). Rephrase complex physiological and diagnostic mechanics into safe, empathetic, patient-friendly communication."
    user_payload = f"SYMPTOMS:\n{agent_1_json_payload}\n\nSYNTHESIS:\n{agent_4_json_payload}"
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_payload}
    ]
    return client.beta.chat.completions.parse(model="gpt-4o-mini", messages=messages, response_format=PatientCommunicationSchema).choices[0].message.parsed